language: java

env:
  global:
    - MVN_VERSION="3.6.2"

jdk:
  - openjdk8
  - openjdk11

matrix:
  fast_finish: true
#  allow_failures:
#    - jdk: openjdk11

cache:
  directories:
  - $HOME/.m2
  - $HOME/downloads
  
before_install:
  # installeer een up-2-date Maven versie
  - wget --directory-prefix=$HOME/downloads/ --no-clobber https://www-eu.apache.org/dist/maven/maven-3/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.zip
  - unzip -qq $HOME/downloads/apache-maven-$MVN_VERSION-bin.zip
  - export M2_HOME=$PWD/apache-maven-$MVN_VERSION
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v --global-toolchains .travis/toolchains.xml

install:
  - mvn -e compile --global-toolchains .travis/toolchains.xml -fae

script:
  - mvn -e verify -B --global-toolchains .travis/toolchains.xml
  
after_success:
  # test of de javadoc compliant is met java-8 strict checks
  - if [ "$TRAVIS_JDK_VERSION" == openjdk8 ]; then
         travis_wait 30 mvn javadoc:javadoc;
         travis_wait 30 mvn javadoc:test-javadoc;
    fi
    
after_script:
  # deploy maven site van master branch als test succes
  - if [ "$TRAVIS_JDK_VERSION" == openjdk8 ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_TEST_RESULT" == 0 ]; then
         travis_wait 50 mvn -B -e -T1 site site:stage
    fi
